namespace :deploy do
  desc "Removes __py_cache__ files generated by sudo execution of python scripts"
  task :clear_py_cache do
    on roles(:all) do
      within current_path do
        execute(:sudo, "rm -rf releases/**/**/__pycache__")
      end
    end
  end
end